### PR TITLE
Feat:made the navbar responsive with animations and added logo

### PR DESCRIPTION
**Pull request by South-IN**
## This pr closes issue #1 

- added a navbar complementing the design of the website.
- added animations to the navbar.
- added logo with a favicon folder containing the logo in different sizes.

### Here is a video of showing the working demo:
https://github.com/user-attachments/assets/2d16fbdf-e0ba-4715-890a-268e8510b6c2

### CODE REVIEW

**Comment by Abhiraj-Sardar** [comment]
great work @South-IN , 

but can you reduce the opacity of the menu in mobile mode, so that the music behind it will not overlay.

Thanks for your contributions so far

**Comment by South-IN** [comment]
How much should I reduce the opacity? Currently it is 0.8 I can go lower but then I think the nav options won't be visible.

**Comment by Abhiraj-Sardar** [comment]
Sorry,
 i mean Increase The Opacity to 1 so that the contents of the navbar will be properly visible.

and please also update the forked repo I made some changes.
Thank You

**Comment by South-IN** [comment]
Oh ok I'll do that

**Comment by South-IN** [comment]
@Abhiraj-Sardar Done

**Comment by South-IN** [comment]
@Abhiraj-Sardar Thank you. 
i'll be looking forward to making more contributions

**Pull request merged**
